# Generated by Django 3.2.12 on 2022-02-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('topic', models.TextField(max_length=1024)),
                ('createdAt', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
